image: hetesiistvan/arduinobuild-base:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/arduinolibraries
  CONTAINER_IMAGE_CI: registry.gitlab.com/$CI_PROJECT_PATH/arduinolibraries-ci

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
- build-image
- build-libraries
- test
- publish
- trigger
- promote_testing
- promote_stable

build-image:
  stage: build-image
  only:
    - master
  script:
    - ./build.sh build-image
    - docker push $CONTAINER_IMAGE_CI:`./build.sh build-version`

build-libraries:
  stage: build-libraries
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - ./build.sh build-libraries

test-unit:
  stage: test
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - ./build.sh build-libraries

push-image:
  stage: publish
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:latest

trigger-library-build:
  stage: trigger
  only:
    - master
  script:
    - curl -X POST -F token=$SERIAL_CONTROL_TEST_BUILD_TOKEN -F ref=master https://gitlab.com/api/v4/projects/7354937/trigger/pipeline

preserve-image:
  stage: promote_testing
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $CONTAINER_IMAGE:`./build.sh build-version`
    - docker push $CONTAINER_IMAGE:`./build.sh build-version`

promote-image-stable:
  stage: promote_stable
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $CONTAINER_IMAGE:stable
    - docker push $CONTAINER_IMAGE:stable