image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - publish
  - trigger
  - promote

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build-image:
  stage: build
  only:
    - master
  script:
    - ./build.sh build-image
    - docker push $CONTAINER_IMAGE/arduinobuild:$CI_COMMIT_SHA

test-image:
  stage: test
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE/arduinobuild:$CI_COMMIT_SHA
    - ./build.sh test-image

tag-and-push-image:
  stage: publish
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE/arduinobuild:$CI_COMMIT_SHA
    - docker tag $CONTAINER_IMAGE/arduinobuild:$CI_COMMIT_SHA $CONTAINER_IMAGE/arduinobuild:latest
    - docker push $CONTAINER_IMAGE/arduinobuild:latest

trigger-library-build:
  stage: trigger
  only:
    - master
  script:
    - docker run --rm appropriate/curl:latest -X POST -F token=$LIBRARY_BUILD_TOKEN -F ref=master https://gitlab.com/api/v4/projects/9940171/trigger/pipeline

promote-image:
  stage: promote
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE/arduinobuild:latest
    - docker tag $CONTAINER_IMAGE/arduinobuild:latest $CONTAINER_IMAGE/arduinobuild:stable
    - docker push $CONTAINER_IMAGE/arduinobuild:stable