image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - publish
  - promote_testing
  - promote_stable

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/gitlabcibase
  CONTAINER_IMAGE_CI: registry.gitlab.com/$CI_PROJECT_PATH/gitlabcibase-ci
  DOCKER_HUB_REGISTRY: https://index.docker.io/v1/
  DOCKER_HUB_IMAGE: hetesiistvan/arduinobuild-base

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build-image:
  stage: build
  only:
    - master
  script:
    - ./build.sh build-image
    - docker push $CONTAINER_IMAGE_CI:`./build.sh build-version`

test-image:
  stage: test
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - ./build.sh test-image

tag-and-push-image:
  stage: publish
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:latest

preserve-image:
  stage: promote_testing
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $CONTAINER_IMAGE:`./build.sh build-version`
    - docker push $CONTAINER_IMAGE:`./build.sh build-version`

promote-image-stable:
  stage: promote_stable
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $CONTAINER_IMAGE:stable
    - docker push $CONTAINER_IMAGE:stable

promote-to-docker-hub:
  stage: promote_stable
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE_CI:`./build.sh build-version`
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $DOCKER_HUB_IMAGE:stable
    - docker tag $CONTAINER_IMAGE_CI:`./build.sh build-version` $DOCKER_HUB_IMAGE:`./build.sh build-version`
    - docker logout
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWD $DOCKER_HUB_REGISTRY
    - docker push $DOCKER_HUB_IMAGE:stable
    - docker push $DOCKER_HUB_IMAGE:`./build.sh build-version`