image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build_and_push:
  stage: build
  only:
    - master
  script:
    - docker build --tag $CONTAINER_IMAGE/arduinobuild:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE/arduinobuild:latest .
    - docker push $CONTAINER_IMAGE/arduinobuild:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE/arduinobuild:latest
