image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
- build-image
- build-libraries
- test
- publish
- trigger
- promote

build-image:
  stage: build-image
  only:
    - master
  script:
    - ./build.sh build-image
    - docker push $CONTAINER_IMAGE/arduinolibraries:$CI_COMMIT_SHA

build-libraries:
  stage: build-libraries
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE/arduinolibraries:$CI_COMMIT_SHA
    - ./build.sh build-libraries

test-unit:
  stage: test
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE/arduinolibraries:$CI_COMMIT_SHA
    - ./build.sh build-libraries

push-image:
  stage: publish
  only:
    - master
  script:
    - docker pull $CONTAINER_IMAGE/arduinolibraries:$CI_COMMIT_SHA
    - docker tag $CONTAINER_IMAGE/arduinolibraries:$CI_COMMIT_SHA $CONTAINER_IMAGE/arduinolibraries:latest
    - docker tag $CONTAINER_IMAGE/arduinolibraries:latest $CONTAINER_IMAGE/arduinolibraries:`./build.sh build-version`
    - docker push $CONTAINER_IMAGE/arduinolibraries:latest
    - docker push $CONTAINER_IMAGE/arduinolibraries:`./build.sh build-version`

trigger-library-build:
  stage: trigger
  only:
    - master
  script:
    - docker run --rm appropriate/curl:latest -X POST -F token=$SERIAL_CONTROL_TEST_BUILD_TOKEN -F ref=master https://gitlab.com/api/v4/projects/7354937/trigger/pipeline

promote-image:
  stage: promote
  only:
    - master
  when: manual
  script:
    - docker pull $CONTAINER_IMAGE/arduinolibraries:latest
    - docker tag $CONTAINER_IMAGE/arduinolibraries:latest $CONTAINER_IMAGE/arduinolibraries:stable
    - docker push $CONTAINER_IMAGE/arduinolibraries:stable